services:
  sen-tunnel-prod:
    image: cloudflare/cloudflared:latest
    container_name: sen-tunnel-prod
    restart: unless-stopped
    command: tunnel --url http://sen-frontend:80
    networks:
      - sen-network

networks:
  sen-network:
    external: true
